name: "Semantic Release"
description: 'Semantic release'
inputs:
  prefix:
    description: 'version prefix'
    required: false
    default: 'v'
  node-version:
    description: 'node version'
    required: false
    default: 20
outputs:
  version:
    description: 'Release version'
    value: ${{ steps.release.outputs.version }}
  tag:
    description: 'Release tag'
    value: ${{ steps.release.outputs.tag }}

runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Run release.sh
      id: release
      shell: bash
      run: |
        ./release.sh "${{ inputs.prefix }}"
